# Generated by Django 2.0.6 on 2019-03-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('where', models.CharField(max_length=50)),
                ('richOrwhat', models.CharField(max_length=50)),
                ('powers', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=50)),
                ('ability_examples', models.TextField(max_length=1000)),
            ],
        ),
    ]
